name: Release Helm Charts

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Helm
      uses: azure/setup-helm@v4.0.0
      with:
        version: 'v3.7.0'

    - name: Configure Git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"

    - name: Package Helm Charts
      run: helm package -d charts/tmp hive-metastore

    - name: Publish Helm Charts on bh-pages branch
      run: |
        git fetch
        git checkout bh-pages
        mv charts/tmp/* charts/
        helm repo index .
        git add -A
        git commit -m "Helm chart release"
        git push
