name: Release Helm Charts

on:
  push:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.7.0'

    - name: Package Helm Charts
      run: |
        mkdir -p charts
        helm package -d gh-charts hive-metastore

    - name: Publish Helm Charts
      run: |
        git fetch
        git stash
        git checkout bh-pages
        git stash pop
        git add -A
        git commit -m "Helm chart release"
        git push
